apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy-app-deployment
  name: dummy-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: dummy-app-deployment
    spec:
      containers:
      - image: superhulcker/dummy-app
        name: dummy-app
        ports:
        - containerPort: 8090
        resources: {}
status: {}
