apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-service
  name: backend-service
spec:
  ports:
  - name: 80-8080
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-pods
  type: NodePort
status:
  loadBalancer: {}
