apiVersion: v1
kind: Secret
metadata:
  name: EXTERNAL_INTGERATION_KEY-secret
data:
  Integration-key: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pods
spec:
  containers:
    - name: dummy-backend
      image: superhulcker/dummy-backend
      env:
       - name: EXTERNAL_INTGERATION_KEY
         valueFrom:
           secretKeyRef:
             name: EXTERNAL_INTGERATION_KEY
             key: Integration-key
