# Creating simple Kubernets cluster nodes #1 Master & 1 workernode
---
- name : Creating Kubernets cluster Nodes 
  hosts: localhost 

  vars:  
    keypair: Linux-amazon
    instance_type: t2.micro
    image: ami-07761f3ae34c4478d 
    wait: yes
    group: Kubernets-sg
    count: 1
    region: us-east-1
    vpc_id: vpc-0c9769badb50cef8d
    subnet_id: subnet-09dd3363516e26246
    AZ: us-east-1a
  


  tasks:
    - name: Create Kubernets Master Instnace 
      amazon.aws.ec2_instance: 
        name: "Kuberents Master" 
        state: running
        wait: yes
        key_name: "{{keypair}}"
        instance_type: "{{instance_type}}" 
        security_group: "{{group}}"
        image_id: "{{image}}"
        region: "{{region}}"
        vpc_subnet_id: "{{subnet_id}}"
        network:
          assign_public_ip: true
        tags:
          group: Kube-master
        volumes: 
          - device_name: /dev/sda1
            ebs:
              volume_size: 20

    - name: Create Kubernets Worker Instnace 
      amazon.aws.ec2_instance: 
        name: "Kuberents Worker" 
        state: running
        wait: yes
        key_name: "{{keypair}}"
        instance_type: "{{instance_type}}"
        security_group: "{{group}}"
        image_id: "{{image}}"
        region: "{{region}}" 
        vpc_subnet_id: "{{subnet_id}}"
        count: 2
        network:
          assign_public_ip: true
        tags:
          group: Kube-worker  
     
